In [64]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# Import the Data

Import the data found in `datasets/inventory_by_county.csv`. This data comes from [realtor.com](https://research.realtor.com/data/inventory-trends/) and details housing information about the most active counties for housing stock in the US. 

After you import the data and run the following cell to create a "state" identifier: 
- take out the `Median Listing Price` as your target column.
- use `train_test_split()` with a test size of `0.33` to create a training and test set for the features and your target column (`Median Listing Price`). You should have four objects at this point.
- identify the number of rows and columns in all four of datasets (`train_x, train_y, test_x, test_y`)

In [143]:
df = pd.read_csv('datasets/inventory_by_county.csv')

# The last line of the csv contains extra information for the reader but not valid data
# We will remove that line and use the .copy() method
# To create a copy of the DataFrame itself
# Instead of referring to a slice or a mask of the original dataframe

df = df.iloc[0:1000, :].copy()
df.head()

Month  CountyFIPS       CountyName  Nielsen Rank Footnote  \
0  2017-09-01      6037.0  Los Angeles, CA           1.0      NaN   
1  2017-09-01     17031.0         Cook, IL           2.0      NaN   
2  2017-09-01     48201.0       Harris, TX           3.0      NaN   
3  2017-09-01      4013.0     Maricopa, AZ           4.0      NaN   
4  2017-09-01      6073.0    San Diego, CA           5.0      NaN   

   Median Listing Price  Median Listing Price M/M  Median Listing Price Y/Y  \
0              649900.0                   -0.0002                    0.0398   
1              277000.0                   -0.0072                    0.0897   
2              299000.0                    0.0007                   -0.0355   
3              329500.0                    0.0015                    0.0444   
4              660200.0                   -0.0139                    0.0541   

   Active Listing Count   Active Listing Count M/M        ...          \
0                16464.0                   -0.0261        ...           
1                26510.0                   -0.0142        ...           
2                15472.0                   -0.1020        ...           
3                18421.0                    0.0013        ...           
4                 6057.0                   -0.0205        ...           

   Pending Listing Count Y/Y  Avg Listing Price  Avg Listing Price M/M  \
0                    -0.2008          1377900.0                -0.0035   
1                    -0.2012           428900.0                -0.0046   
2                    -0.0535           446900.0                 0.0182   
3                    -0.2857           515200.0                 0.0043   
4                     0.1176          1147100.0                -0.0126   

   Avg Listing Price Y/Y  Total Listing Count  Total Listing Count M/M  \
0                 0.1149              19577.0                  -0.0306   
1                 0.0701              29420.0                  -0.0202   
2                -0.0225              21676.0                  -0.0888   
3                 0.0658              18426.0                   0.0013   
4                 0.0615               6076.0                  -0.0224   

   Total Listing Count Y/Y  Pending Ratio  Pending Ratio M/M  \
0                  -0.1578         0.1891            -0.0055   
1                  -0.0683         0.1098            -0.0067   
2                   0.0114         0.4010             0.0204   
3                  -0.0860         0.0003             0.0000   
4                  -0.1880         0.0031            -0.0019   

   Pending Ratio Y/Y  
0            -0.0122  
1            -0.0207  
2            -0.0397  
3            -0.0001  
4             0.0009  

[5 rows x 35 columns]

In [144]:
# continue here to extract Median Listing Price and to split the data using train_test_split()
#reshape(-1, 1) 
#reshape command to coerce the array to have the maximum possible value (-1) 
#for the number of rows and 1 element per row.
y=df['Median Listing Price'].values.reshape(-1, 1)
y.shape

(1000, 1)

In [145]:
len(df.columns)

35

In [146]:
X = df.drop('Median Listing Price',axis=1)

In [147]:
X=df[[col for col in df.columns if col != 'Median Listing Price']]

In [148]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.33)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(670, 34) (330, 34) (670, 1) (330, 1)


# Question 1

Investigate the pattern of missing values in the dataset. What do you think should be done with those missing values? Is it appropriate to use `Imputer` to address any missing rows? Why or why not?

In [149]:
# Convert this cell to markdown and write your answer here.
X_train.isnull().sum()

Month                          0
CountyFIPS                     0
CountyName                     0
Nielsen Rank                   0
Footnote                     576
Median Listing Price M/M       0
Median Listing Price Y/Y       0
Active Listing Count           0
Active Listing Count M/M       0
Active Listing Count Y/Y       0
Days on Market                 0
Days on Market M/M             0
Days on Market Y/Y             0
New Listing Count              0
New Listing Count M/M          0
New Listing Count Y/Y          0
Price Increase Count           0
Price Increase Count M/M     120
Price Increase Count Y/Y     128
Price Decrease Count           0
Price Decrease Count M/M       0
Price Decrease Count Y/Y       0
Pending Listing Count          0
Pending Listing Count M/M    127
Pending Listing Count Y/Y    133
Avg Listing Price              0
Avg Listing Price M/M          0
Avg Listing Price Y/Y          0
Total Listing Count            0
Total Listing Count M/M        0
Total List

In [150]:
from sklearn.preprocessing import Imputer

In [151]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 670 entries, 593 to 495
Data columns (total 34 columns):
Month                        670 non-null object
CountyFIPS                   670 non-null float64
CountyName                   670 non-null object
Nielsen Rank                 670 non-null float64
Footnote                     94 non-null object
Median Listing Price M/M     670 non-null float64
Median Listing Price Y/Y     670 non-null float64
Active Listing Count         670 non-null float64
Active Listing Count M/M     670 non-null float64
Active Listing Count Y/Y     670 non-null float64
Days on Market               670 non-null float64
Days on Market M/M           670 non-null float64
Days on Market Y/Y           670 non-null float64
New Listing Count            670 non-null float64
New Listing Count M/M        670 non-null float64
New Listing Count Y/Y        670 non-null float64
Price Increase Count         670 non-null float64
Price Increase Count M/M     550 non-null float

In [155]:
X_train = X_train.loc[:,[col for col in X_train.columns if col not in ['Footnote','CountyName','Month']]]

In [156]:
X_train.columns

Index(['CountyFIPS', 'Nielsen Rank', 'Median Listing Price M/M',
       'Median Listing Price Y/Y', 'Active Listing Count ',
       'Active Listing Count M/M', 'Active Listing Count Y/Y',
       'Days on Market ', 'Days on Market M/M', 'Days on Market Y/Y',
       'New Listing Count ', 'New Listing Count M/M', 'New Listing Count Y/Y',
       'Price Increase Count ', 'Price Increase Count M/M',
       'Price Increase Count Y/Y', 'Price Decrease Count ',
       'Price Decrease Count M/M', 'Price Decrease Count Y/Y',
       'Pending Listing Count ', 'Pending Listing Count M/M',
       'Pending Listing Count Y/Y', 'Avg Listing Price',
       'Avg Listing Price M/M', 'Avg Listing Price Y/Y', 'Total Listing Count',
       'Total Listing Count M/M', 'Total Listing Count Y/Y', 'Pending Ratio',
       'Pending Ratio M/M', 'Pending Ratio Y/Y'],
      dtype='object')

In [157]:
im = Imputer(strategy='median')
im.fit(X_train)

Imputer(axis=0, copy=True, missing_values='NaN', strategy='median', verbose=0)

In [158]:
X_train = pd.DataFrame(im.transform(X_train),columns = X_train.columns)

In [159]:
im.statistics_

array([  3.40060000e+04,   4.79500000e+02,  -2.00000000e-04,
         6.72500000e-02,   7.20500000e+02,  -1.12000000e-02,
        -9.56000000e-02,   7.10000000e+01,   5.98500000e-02,
        -8.92500000e-02,   1.84000000e+02,  -1.01500000e-01,
        -5.25000000e-03,   6.00000000e+00,  -1.38100000e-01,
        -2.08500000e-02,   1.55000000e+02,  -5.40000000e-02,
        -2.80000000e-02,   3.85000000e+01,  -5.59000000e-02,
        -4.23000000e-02,   2.85550000e+05,   7.00000000e-04,
         6.15500000e-02,   8.17500000e+02,  -1.64500000e-02,
        -8.35500000e-02,   6.19500000e-02,  -5.00000000e-04,
         2.50000000e-04])

In [160]:
X_train.isnull().sum()

CountyFIPS                   0
Nielsen Rank                 0
Median Listing Price M/M     0
Median Listing Price Y/Y     0
Active Listing Count         0
Active Listing Count M/M     0
Active Listing Count Y/Y     0
Days on Market               0
Days on Market M/M           0
Days on Market Y/Y           0
New Listing Count            0
New Listing Count M/M        0
New Listing Count Y/Y        0
Price Increase Count         0
Price Increase Count M/M     0
Price Increase Count Y/Y     0
Price Decrease Count         0
Price Decrease Count M/M     0
Price Decrease Count Y/Y     0
Pending Listing Count        0
Pending Listing Count M/M    0
Pending Listing Count Y/Y    0
Avg Listing Price            0
Avg Listing Price M/M        0
Avg Listing Price Y/Y        0
Total Listing Count          0
Total Listing Count M/M      0
Total Listing Count Y/Y      0
Pending Ratio                0
Pending Ratio M/M            0
Pending Ratio Y/Y            0
dtype: int64

# Question 2

Use the `Active Listing Count ` feature and the `Binarizer` preprocessing object to create a dummy variable coded 1 if the count of active listings is above 10,000 units. Store the transformed data from the training set in a variable called `training_active_listing_dummy`

In [161]:
from sklearn.preprocessing import Binarizer, \
    OneHotEncoder, PolynomialFeatures, StandardScaler, \
    MinMaxScaler, RobustScaler

In [162]:
training_active_listing=Binarizer(10000)
training_active_listing.fit(X_train['Active Listing Count '].values.reshape(-1,1))
training_active_listing_dummy=training_active_listing.transform(
    X_train['Active Listing Count '].values.reshape(-1,1))

In [163]:
print(training_active_listing_dummy[0:5],training_active_listing_dummy.mean())

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] 0.00746268656716


In [164]:
training_active_listing_dummy.shape

(670, 1)

# Question 3

The Pending Ratio of a county is the proportion of houses that are under contract to be sold, but have not been finalized yet. Your boss believes that the best way to model this is by including both the ratio and the $\text{ratio}^2$ -- this would let us investigate a non-linear relationship. 

Use `PolynomialFeatures` to create a pending ratio and a $\text{pending ratio}^2$ term. Do not include an intercept term. Save this 2-dimensional array in a variable called `training_pending_ratio`

In [165]:
poly_features = PolynomialFeatures(2, include_bias=False)
poly_features.fit(X_train['Pending Ratio'].values.reshape(-1, 1))

training_pending_ratio = poly_features.transform(
    X_train['Pending Ratio'].values.reshape(-1, 1))

print(training_pending_ratio[0:5, :])


[[ 0.          0.        ]
 [ 0.097       0.009409  ]
 [ 0.044       0.001936  ]
 [ 0.0188      0.00035344]
 [ 0.          0.        ]]


# Question 4

Join the variables you have transformed in numpy. They should be the following:

- `training_active_listing_dummy`
- `training_pending_ratio`

What is the shape of the new numpy array?

In [166]:
#X_train.append(training_active_listing_dummy)
new_array = np.concatenate((training_active_listing_dummy,training_pending_ratio),axis=1)

In [167]:
new_array.shape

(670, 3)

In [168]:
training_active_listing_dummy.shape

(670, 1)

In [169]:
training_pending_ratio.shape

(670, 2)

# Question 5

Instantiate a `LinearRegression` object and fit a model using the new training array above and the training target column you created when you imported the data. What is the $R^2$ score using the training data?

In [190]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(new_array, y_train)
print(lr.score(new_array, y_train))

0.0742310266243


In [179]:
training_active_listing.transform(X_test)

array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       ..., 
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 1.,  0.,  0., ...,  0.,  0.,  0.]])

# Question 6

Using the fit objects that you created in questions 2, 3, and 4, do the following:

1. Transform the holdout (test) data that you created when you imported the data
2. Use numpy to join the transformed holdout (test) data. 
3. Score your fit `LinearRegression` object using the new holdout data. What happens to your $R^2$ value?

In [172]:
X_test = X_test.loc[:,[col for col in X_test.columns if col not in ['Footnote','CountyName','Month']]]

In [173]:
X_test.columns

Index(['CountyFIPS', 'Nielsen Rank', 'Median Listing Price M/M',
       'Median Listing Price Y/Y', 'Active Listing Count ',
       'Active Listing Count M/M', 'Active Listing Count Y/Y',
       'Days on Market ', 'Days on Market M/M', 'Days on Market Y/Y',
       'New Listing Count ', 'New Listing Count M/M', 'New Listing Count Y/Y',
       'Price Increase Count ', 'Price Increase Count M/M',
       'Price Increase Count Y/Y', 'Price Decrease Count ',
       'Price Decrease Count M/M', 'Price Decrease Count Y/Y',
       'Pending Listing Count ', 'Pending Listing Count M/M',
       'Pending Listing Count Y/Y', 'Avg Listing Price',
       'Avg Listing Price M/M', 'Avg Listing Price Y/Y', 'Total Listing Count',
       'Total Listing Count M/M', 'Total Listing Count Y/Y', 'Pending Ratio',
       'Pending Ratio M/M', 'Pending Ratio Y/Y'],
      dtype='object')

In [177]:
X_test = pd.DataFrame(im.transform(X_test),columns=X_train.columns)

In [178]:
X_test.head()

CountyFIPS  Nielsen Rank  Median Listing Price M/M  \
0     47155.0         608.0                    0.0004   
1     27035.0         772.0                   -0.0104   
2     56025.0         659.0                    0.0048   
3     22101.0         939.0                    0.0013   
4     25017.0          22.0                    0.0079   

   Median Listing Price Y/Y  Active Listing Count   Active Listing Count M/M  \
0                    0.1116                 1862.0                   -0.0090   
1                    0.1023                  766.0                   -0.0316   
2                   -0.0026                  565.0                   -0.0325   
3                    0.0445                  175.0                   -0.0057   
4                    0.0681                 2966.0                    0.0669   

   Active Listing Count Y/Y  Days on Market   Days on Market M/M  \
0                   -0.2242             93.0              0.0220   
1                   -0.0870             92.0              0.0952   
2                    0.0762             63.0              0.1250   
3                    0.7327            105.0              0.1932   
4                   -0.1345             40.0             -0.1111   

   Days on Market Y/Y        ...          Pending Listing Count Y/Y  \
0             -0.1842        ...                            -0.0726   
1             -0.0707        ...                             0.0921   
2             -0.1250        ...                            -0.0423   
3             -0.2045        ...                             0.3333   
4             -0.1837        ...                            -0.0423   

   Avg Listing Price  Avg Listing Price M/M  Avg Listing Price Y/Y  \
0           321500.0                 0.0126                 0.1222   
1           417900.0                 0.0034                 0.1219   
2           269200.0                -0.0033                 0.0011   
3           196400.0                -0.0150                -0.1052   
4           876600.0                 0.0099                 0.0828   

   Total Listing Count  Total Listing Count M/M  Total Listing Count Y/Y  \
0               2079.0                  -0.0048                  -0.2107   
1                932.0                  -0.0557                  -0.0595   
2                565.0                  -0.0325                   0.0762   
3                187.0                  -0.0260                   0.7000   
4               2967.0                   0.0669                  -0.1342   

   Pending Ratio  Pending Ratio M/M  Pending Ratio Y/Y  
0         0.1165             0.0048             0.0190  
1         0.2167            -0.0311             0.0355  
2         0.0000             0.0000             0.0000  
3         0.0686            -0.0223            -0.0205  
4         0.0003             0.0000             0.0003  

[5 rows x 31 columns]

In [180]:
testing_active_listing=Binarizer(10000)
testing_active_listing.fit(X_test['Active Listing Count '].values.reshape(-1,1))
testing_active_listing_dummy=testing_active_listing.transform(
    X_test['Active Listing Count '].values.reshape(-1,1))

In [181]:
print(testing_active_listing_dummy[0:5],testing_active_listing_dummy.mean())

[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]] 0.00909090909091


In [184]:
poly_features = PolynomialFeatures(2, include_bias=False)
poly_features.fit(X_test['Pending Ratio'].values.reshape(-1, 1))

test_pending_ratio = poly_features.transform(
    X_test['Pending Ratio'].values.reshape(-1, 1))

print(test_pending_ratio[0:5, :])

[[  1.16500000e-01   1.35722500e-02]
 [  2.16700000e-01   4.69588900e-02]
 [  0.00000000e+00   0.00000000e+00]
 [  6.86000000e-02   4.70596000e-03]
 [  3.00000000e-04   9.00000000e-08]]


In [193]:
testing_array = np.concatenate((testing_active_listing_dummy,test_pending_ratio),axis=1)

In [194]:
testing_array.shape

(330, 3)

In [195]:
y_test.shape

(330, 1)

In [198]:

print(lr.score(testing_array, y_test))

0.0564179928799


# Bonus: Question 7

This question will require external research!

Import `StandardScaler` and answer the following questions:

1. Scale the training data and refit the linear regression. Does your $R^2$ change? Why or why not?
2. Compare the coefficients in your linear regression between the standardized and the unstandardized versions. What is the difference? How do you interpret the coefficients in each case?
3. Standardize your test data and look at the $R^2$ score between the standardized and unstandardized versions of your model. Is there a difference? Why or why not?

# Bonus: Question 8

This question is open-ended!

1. Use the remaining columns in the data. Use different features and transformations to create a model with the highest $R^2$ **in the training set** that you can. Compare the differences in feature extraction, etc. using cross-validation (`cross_val_score` or `KFolds`). Do not worry about using the preprocessing library at this point.
2. Apply these same transformations to the test dataset. How does the model score now?
3. Once you are satisfied with your model, refactor your code where appropriate to use sklearn preprocessing libraries. 