In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.decomposition import TruncatedSVD
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

# Intro to NLP Lab

In this lab, you'll be classifying randomly selected tweets from political officials into whether or not they are partisan tweets or neutral. In the following import statement, we're selecting only the columns that are important, but there may be more useful features in that set. Feel free to explore. 

In [2]:
df = pd.read_csv('datasets/political_media.csv',
                usecols=[7, 20])
df.head()

bias                                               text
0  partisan  RT @nowthisnews: Rep. Trey Radel (R- #FL) slam...
1  partisan  VIDEO - #Obamacare:  Full of Higher Costs and ...
2   neutral  Please join me today in remembering our fallen...
3   neutral  RT @SenatorLeahy: 1st step toward Senate debat...
4  partisan  .@amazon delivery #drones show need to update ...

## Set up

Please split the dataset into a training and test set and convert the `bias` feature into 0s and 1s.

In [3]:
df['bias'] = df['bias'].apply(lambda x: 1 if x == 'partisan' else 0)
X_train, X_test, y_train, y_test = train_test_split(df['text'].values,
                                                   df['bias'].values)

## Modeling

Please try the following techniques to transform the data. For each technique, do the following:

1. Transform the training data
2. Fit a `RandomForestClassifier` to the transformed training data
3. Transform the test data
4. Discuss the goodness of fit of your model using the test data and a classification report and confusion matrix

### 1. `CountVectorizer()`

In [4]:
cv = CountVectorizer()
cv.fit(X_train)

X_train_cv = cv.transform(X_train)
X_test_cv = cv.transform(X_test)

rf = RandomForestClassifier()
rf.fit(X_train_cv, y_train)
print(rf.score(X_test_cv, y_test))
predictions = rf.predict(X_test_cv)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.7552
[[895  33]
 [273  49]]
             precision    recall  f1-score   support

          0       0.77      0.96      0.85       928
          1       0.60      0.15      0.24       322

avg / total       0.72      0.76      0.70      1250



### 2. `CountVectorizer()` with your choice of `min_df` and `max_df`

In [5]:
cv = CountVectorizer(min_df=0.10, max_df=0.90)
cv.fit(X_train)

X_train_cv = cv.transform(X_train)
X_test_cv = cv.transform(X_test)

rf = RandomForestClassifier()
rf.fit(X_train_cv, y_train)
print(rf.score(X_test_cv, y_test))
predictions = rf.predict(X_test_cv)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.716
[[841  87]
 [268  54]]
             precision    recall  f1-score   support

          0       0.76      0.91      0.83       928
          1       0.38      0.17      0.23       322

avg / total       0.66      0.72      0.67      1250



### 3. `CountVectorizer()` with English stop words

In [6]:
cv = CountVectorizer(stop_words='english')
cv.fit(X_train)

X_train_cv = cv.transform(X_train)
X_test_cv = cv.transform(X_test)

rf = RandomForestClassifier()
rf.fit(X_train_cv, y_train)
print(rf.score(X_test_cv, y_test))
predictions = rf.predict(X_test_cv)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.748
[[868  60]
 [255  67]]
             precision    recall  f1-score   support

          0       0.77      0.94      0.85       928
          1       0.53      0.21      0.30       322

avg / total       0.71      0.75      0.71      1250



### 4. `TfidfVectorizer()` 

In [7]:
tfidf = TfidfVectorizer()
tfidf.fit(X_train)

X_train_tfidf = tfidf.transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

rf = RandomForestClassifier()
rf.fit(X_train_tfidf, y_train)
print(rf.score(X_test_tfidf, y_test))
predictions = rf.predict(X_test_tfidf)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.7488
[[870  58]
 [256  66]]
             precision    recall  f1-score   support

          0       0.77      0.94      0.85       928
          1       0.53      0.20      0.30       322

avg / total       0.71      0.75      0.71      1250



### 5. `TfidfVectorizer()` with English stop words

In [8]:
tfidf = TfidfVectorizer(stop_words='english')
tfidf.fit(X_train)

X_train_tfidf = tfidf.transform(X_train)
X_test_tfidf = tfidf.transform(X_test)

rf = RandomForestClassifier()
rf.fit(X_train_tfidf, y_train)
print(rf.score(X_test_tfidf, y_test))
predictions = rf.predict(X_test_tfidf)
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

0.7472
[[861  67]
 [249  73]]
             precision    recall  f1-score   support

          0       0.78      0.93      0.84       928
          1       0.52      0.23      0.32       322

avg / total       0.71      0.75      0.71      1250



### Moving forward

With the remainder of your time, please try and find the best model and data transformation to predict partisan tweets. This is a challenging data set and can be approached from a number of ways.

Some techniques to try are:

1. Different types of data transformation 
2. Custom preprocessors for `CountVectorizer`
3. Custom stopword lists
4. Use of a dimensionality reduction technique (like `TruncatedSVD`)
5. Optimizing hyperparameters using `GridSearchCV`
6. Trying a different modeling technique such as `KNeighborsClassifier` or `LogisticRegression`

```
Instructor answer:

This section is exceptionally open ended. Please challenge yourself to try multiple techniques and compare the results.
```